<a href="https://colab.research.google.com/github/Ezzaldin97/pytorch-coding/blob/main/LinearRegression_in_numpy_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import torch
import numpy as np
import numpy as np
from numpy.random import random
from mpl_toolkits.mplot3d import Axes3D

torch.__version__

'2.0.0+cu118'

In [2]:
x = random((30,2))
weights = np.array([[2, -3]], dtype = np.float16)
b = np.array([1], dtype = np.float16)

In [3]:
x.shape

(30, 2)

In [4]:
y = np.dot(x, [2., -3.]) + 1
y = y.reshape(-1, 1)
y

array([[ 0.93976215],
       [ 0.02434462],
       [ 0.08039168],
       [ 1.5002215 ],
       [ 1.14302064],
       [ 0.11809923],
       [ 2.58006522],
       [ 0.92832671],
       [ 2.01561069],
       [ 0.12534904],
       [ 2.08160314],
       [-0.93065577],
       [-0.65141736],
       [ 1.22488698],
       [-0.15569628],
       [ 1.41021714],
       [ 2.00527227],
       [-0.2087599 ],
       [ 0.60392554],
       [ 1.07941942],
       [-0.28899717],
       [ 0.17633531],
       [-1.51756306],
       [-0.77860259],
       [ 1.29081597],
       [ 1.07168173],
       [ 1.42321744],
       [ 0.78026244],
       [-0.13846486],
       [-1.2772521 ]])

In [5]:
# define learnable weights.
# random intialization for W and b

W = random(2).reshape(1, -1)
b_init = random(1).reshape(-1, 1)

print(f"intialized weights: {W}, {b_init}")

intialized weights: [[0.93086268 0.98144221]], [[0.67178206]]


In [6]:
def forward(W, b, X):
  return X @ W.T +b
y_hat = forward(W, b, x)
y_hat

array([[2.05712832],
       [1.32365771],
       [2.15151457],
       [2.25799384],
       [1.08071281],
       [1.6399012 ],
       [1.93880159],
       [1.9245289 ],
       [1.75214286],
       [2.26519005],
       [1.61546524],
       [1.98834992],
       [2.1451757 ],
       [1.51387152],
       [1.58728088],
       [1.46857939],
       [1.65455939],
       [2.4028588 ],
       [2.31964251],
       [1.55851195],
       [1.61733357],
       [2.63071005],
       [1.89144548],
       [1.85504375],
       [1.34634378],
       [1.79748713],
       [1.32228793],
       [2.5484004 ],
       [1.51626786],
       [2.14487546]])

In [7]:
def loss(y_hat, y):
  return np.sum((y_hat - y)**2)
loss(y_hat, y)

92.3036494268948

In [8]:
# dl/dW, dl/db_init
def grad(y_hat, y, X):
  dW = (y_hat - y).T @ X
  db = np.sum((y_hat - y))
  return 2*dW, 2*db

In [9]:
grad(y_hat, y, x)

(array([[29.29514833, 54.23357262]]), 77.32128561189221)

In [10]:
lr = 0.001
for epoch in range(1000):
  y_hat = forward(W, b_init, x)
  l = loss(y_hat, y)
  dW, db = grad(y_hat, y, x)
  # gradient descent step
  W = W - lr * dW
  b_init = b_init - lr * db
  print("progress:", "epoch:", epoch, "loss", l)
# After training
print("estimation of the parameters:", W, b_init)

progress: epoch: 0 loss 70.15722711561119
progress: epoch: 1 loss 64.57054261248092
progress: epoch: 2 loss 59.83671189873473
progress: epoch: 3 loss 55.81776820142183
progress: epoch: 4 loss 52.39814151219098
progress: epoch: 5 loss 49.48102208163298
progress: epoch: 6 loss 46.985314370803856
progress: epoch: 7 loss 44.84308558769412
progress: epoch: 8 loss 42.997428503135716
progress: epoch: 9 loss 41.400671279804286
progress: epoch: 10 loss 40.01287796997699
progress: epoch: 11 loss 38.800592486308105
progress: epoch: 12 loss 37.7357865130336
progress: epoch: 13 loss 36.79497824390237
progress: epoch: 14 loss 35.95849420978717
progress: epoch: 15 loss 35.20985096257901
progress: epoch: 16 loss 34.5352371543635
progress: epoch: 17 loss 33.9230797107509
progress: epoch: 18 loss 33.36368044403758
progress: epoch: 19 loss 32.84891166892231
progress: epoch: 20 loss 32.37196124056535
progress: epoch: 21 loss 31.92711899031282
progress: epoch: 22 loss 31.509597837371633
progress: epoch: 23

In [11]:
# now create Linear Regression and Gradient Descent using pytorch
dtype = torch.cuda.FloatTensor

In [35]:
x_t = torch.from_numpy(x).type(dtype)
y_t = torch.from_numpy(y).type(dtype)

In [36]:
W = random(2).reshape(1, -1)
b_init = random(1).reshape(-1, 1)
print(f"intialized weights: {W}, {b_init}")
W_t = torch.from_numpy(W).type(dtype)
b_t = torch.from_numpy(b_init).type(dtype)
print(f"intialized weights as Tensors: {W_t}, {b_t}")

intialized weights: [[0.42220785 0.83675717]], [[0.66164985]]
intialized weights as Tensors: tensor([[0.4222, 0.8368]], device='cuda:0'), tensor([[0.6616]], device='cuda:0')


In [37]:
def forward(W, b, X):
  return torch.mm(X, W.t())+b
y_hat = forward(W_t, b_t, x_t)

In [38]:
def loss(y_hat, y):
  return (y_hat - y).pow(2).sum()
l = loss(y_hat, y_t)

In [39]:
def grad(y_hat, y, X):
  dW = torch.mm((y_hat - y).t(), X)
  db = (y_hat - y).sum()
  return 2*dW, 2*db

In [40]:
# more precise than numpy
lr = 1e-2
for epoch in range(1000):
  y_hat = forward(W_t, b_t, x_t)
  l = loss(y_hat, y_t)
  if l <= 1e-5:
    print("Converged!!!")
    print("progress:", "epoch:", epoch, "loss",l)
    break
  else:
    dw_t, db_t = grad(y_hat, y_t, x_t)
    W_t = W_t - lr * dw_t
    b_t = b_t - lr * db_t
  print("progress:", "epoch:", epoch, "loss",l)
# After training
print("estimation of the parameters:", W_t, b_t)

progress: epoch: 0 loss tensor(55.8100, device='cuda:0')
progress: epoch: 1 loss tensor(36.7293, device='cuda:0')
progress: epoch: 2 loss tensor(33.0020, device='cuda:0')
progress: epoch: 3 loss tensor(29.9360, device='cuda:0')
progress: epoch: 4 loss tensor(27.1624, device='cuda:0')
progress: epoch: 5 loss tensor(24.6469, device='cuda:0')
progress: epoch: 6 loss tensor(22.3651, device='cuda:0')
progress: epoch: 7 loss tensor(20.2953, device='cuda:0')
progress: epoch: 8 loss tensor(18.4178, device='cuda:0')
progress: epoch: 9 loss tensor(16.7147, device='cuda:0')
progress: epoch: 10 loss tensor(15.1697, device='cuda:0')
progress: epoch: 11 loss tensor(13.7681, device='cuda:0')
progress: epoch: 12 loss tensor(12.4965, device='cuda:0')
progress: epoch: 13 loss tensor(11.3429, device='cuda:0')
progress: epoch: 14 loss tensor(10.2962, device='cuda:0')
progress: epoch: 15 loss tensor(9.3466, device='cuda:0')
progress: epoch: 16 loss tensor(8.4850, device='cuda:0')
progress: epoch: 17 loss t

In [42]:
# implement linear regression and gradient descent using Autograd...
W = random(2).reshape(1, -1)
b_init = random(1).reshape(-1, 1)
print(f"intialized weights: {W}, {b_init}")
W_t = torch.from_numpy(W).type(dtype)
b_t = torch.from_numpy(b_init).type(dtype)
W_t.requires_grad_()
b_t.requires_grad_()
print(f"intialized weights as Tensors: {W_t}, {b_t}")

intialized weights: [[0.96124238 0.33311662]], [[0.28585037]]
intialized weights as Tensors: tensor([[0.9612, 0.3331]], device='cuda:0', requires_grad=True), tensor([[0.2859]], device='cuda:0', requires_grad=True)


In [45]:
for epoch in range(300):
  y_hat = torch.mm(x_t, W_t.t()) + b_t
  loss = (y_hat - y_t).pow(2).sum()

  loss.backward()
  with torch.no_grad():
    W_t -= lr * W_t.grad
    b_t -= lr * b_t.grad
  # manually set the gradient to zero.
  W_t.grad.zero_()
  b_t.grad.zero_()
  print("progress:", "epoch:", epoch, "loss",loss.data.item())
# After training
print("estimation of the parameters:", W_t.data, b_t.data.t())

progress: epoch: 0 loss 33.11903762817383
progress: epoch: 1 loss 26.545928955078125
progress: epoch: 2 loss 24.045360565185547
progress: epoch: 3 loss 21.854766845703125
progress: epoch: 4 loss 19.867050170898438
progress: epoch: 5 loss 18.061668395996094
progress: epoch: 6 loss 16.421749114990234
progress: epoch: 7 loss 14.932035446166992
progress: epoch: 8 loss 13.5786771774292
progress: epoch: 9 loss 12.349108695983887
progress: epoch: 10 loss 11.231931686401367
progress: epoch: 11 loss 10.216796875
progress: epoch: 12 loss 9.294320106506348
progress: epoch: 13 loss 8.455978393554688
progress: epoch: 14 loss 7.694040298461914
progress: epoch: 15 loss 7.001488208770752
progress: epoch: 16 loss 6.371952056884766
progress: epoch: 17 loss 5.799652099609375
progress: epoch: 18 loss 5.2793402671813965
progress: epoch: 19 loss 4.806252479553223
progress: epoch: 20 loss 4.376064777374268
progress: epoch: 21 loss 3.984851837158203
progress: epoch: 22 loss 3.629049777984619
progress: epoch: 