<a href="https://colab.research.google.com/github/Ezzaldin97/pytorch-coding/blob/main/LinearRegression_in_numpy_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline
import torch
import numpy as np
import numpy as np
from numpy.random import random
from mpl_toolkits.mplot3d import Axes3D

torch.__version__

'2.0.0+cu118'

In [51]:
x = random((30,2))
weights = np.array([[2, -3]], dtype = np.float16)
b = np.array([1], dtype = np.float16)

In [52]:
x.shape

(30, 2)

In [53]:
y = np.dot(x, [2., -3.]) + 1
y = y.reshape(-1, 1)
y

array([[-0.59259981],
       [ 1.22183307],
       [-0.10497906],
       [ 2.6477013 ],
       [ 1.95668955],
       [ 2.61769491],
       [ 1.57299121],
       [ 1.87451338],
       [-0.72433483],
       [-0.46978118],
       [ 0.63383465],
       [-1.13878464],
       [ 0.36537163],
       [ 0.56809381],
       [-0.77308636],
       [ 0.91375626],
       [ 0.65511545],
       [ 0.72918235],
       [ 0.19637065],
       [ 1.08187813],
       [ 0.4851423 ],
       [ 0.77835146],
       [-0.1293633 ],
       [ 0.5784345 ],
       [ 0.57672299],
       [-0.56115856],
       [ 1.2002067 ],
       [ 2.24134895],
       [ 2.2912383 ],
       [-1.00002314]])

In [100]:
# define learnable weights.
# random intialization for W and b

W = random(2).reshape(1, -1)
b_init = random(1).reshape(-1, 1)

print(f"intialized weights: {W}, {b_init}")

intialized weights: [[0.63981972 0.22438981]], [[0.14913375]]


In [101]:
def forward(W, b, X):
  return X @ W.T +b
y_hat = forward(W, b, x)
y_hat

array([[1.30824362],
       [1.32183891],
       [1.77902733],
       [1.53707073],
       [1.3760688 ],
       [1.52404863],
       [1.33166471],
       [1.57352913],
       [1.60665729],
       [1.22922138],
       [1.0532691 ],
       [1.38388126],
       [1.66909793],
       [1.28494398],
       [1.22257195],
       [1.66069137],
       [1.10865358],
       [1.35723677],
       [1.75433524],
       [1.339675  ],
       [1.60526271],
       [1.13527769],
       [1.13010146],
       [1.30236671],
       [1.34106757],
       [1.56057855],
       [1.21609984],
       [1.53240965],
       [1.58776964],
       [1.37671214]])

In [102]:
def loss(y_hat, y):
  return np.sum((y_hat - y)**2)
loss(y_hat, y)

50.02107763134114

In [103]:
# dl/dW, dl/db_init
def grad(y_hat, y, X):
  dW = (y_hat - y).T @ X
  db = np.sum((y_hat - y))
  return 2*dW, 2*db

In [104]:
grad(y_hat, y, x)

(array([[16.27305352, 37.89133728]]), 45.03402393598894)

In [105]:
lr = 0.001
for epoch in range(1000):
  y_hat = forward(W, b_init, x)
  l = loss(y_hat, y)
  dW, db = grad(y_hat, y, x)
  # gradient descent step
  W = W - lr * dW
  b_init = b_init - lr * db
  print("progress:", "epoch:", epoch, "loss", l)
# After training
print("estimation of the parameters:", W, b_init)

progress: epoch: 0 loss 33.422347799451536
progress: epoch: 1 loss 33.073433920418864
progress: epoch: 2 loss 32.72900854926768
progress: epoch: 3 loss 32.3888754388439
progress: epoch: 4 loss 32.05286536856135
progress: epoch: 5 loss 31.720831699249626
progress: epoch: 6 loss 31.39264666811377
progress: epoch: 7 loss 31.06819830048403
progress: epoch: 8 loss 30.747387835583964
progress: epoch: 9 loss 30.4301275806701
progress: epoch: 10 loss 30.116339122167844
progress: epoch: 11 loss 29.80595183432212
progress: epoch: 12 loss 29.498901635792482
progress: epoch: 13 loss 29.19512995288259
progress: epoch: 14 loss 28.894582854977628
progress: epoch: 15 loss 28.59721033349959
progress: epoch: 16 loss 28.302965700471216
progress: epoch: 17 loss 28.011805086763278
progress: epoch: 18 loss 27.723687023420116
progress: epoch: 19 loss 27.43857209222526
progress: epoch: 20 loss 27.156422633974834
progress: epoch: 21 loss 26.87720250484795
progress: epoch: 22 loss 26.600876872864866
progress: e