<a href="https://colab.research.google.com/github/Ezzaldin97/pytorch-coding/blob/main/pyTorch_DL_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [32]:
x = torch.randn(2, 3, requires_grad = True)
print(x)

tensor([[-1.0580,  2.0594, -0.0662],
        [-0.1583, -1.0457,  1.0989]], requires_grad=True)


In [33]:
y = torch.add(x, 2)
y

tensor([[0.9420, 4.0594, 1.9338],
        [1.8417, 0.9543, 3.0989]], grad_fn=<AddBackward0>)

In [34]:
# forward
z = x * x * 2
z

tensor([[2.2387, 8.4821, 0.0088],
        [0.0501, 2.1871, 2.4152]], grad_fn=<MulBackward0>)

In [35]:
# grad can be created for scalar outputs....
# create a Tensor v
v = torch.tensor([[0.1, 0.001, 1.0],[1.0, 0.0001, 0.1]], dtype = torch.float32)
z.backward(v) #dz/dx
print(x.grad) 

tensor([[-4.2320e-01,  8.2375e-03, -2.6488e-01],
        [-6.3333e-01, -4.1829e-04,  4.3956e-01]])


In [38]:
# prevent error while optimization
# x.requires_grad_(False)
# x.detach()
# with
x = torch.randn(2, 3, requires_grad = True)
print(x)
x.requires_grad_(False)
x

tensor([[-1.6357, -0.9596, -0.2488],
        [-0.7869, -0.4407, -1.4513]], requires_grad=True)


tensor([[-1.6357, -0.9596, -0.2488],
        [-0.7869, -0.4407, -1.4513]])

In [37]:
x = torch.randn(2, 3, requires_grad = True)
print(x)
print(x.detach())

tensor([[ 0.0042, -1.8086, -1.1950],
        [-0.5712,  0.0036, -2.1034]], requires_grad=True)
tensor([[ 0.0042, -1.8086, -1.1950],
        [-0.5712,  0.0036, -2.1034]])


In [40]:
x = torch.randn(2, 3, requires_grad = True)
print(x)
with torch.no_grad():
  y = x + 2
  print(y)

tensor([[-0.3038,  0.0337, -1.2638],
        [ 0.4875,  1.4212,  0.1066]], requires_grad=True)
tensor([[1.6962, 2.0337, 0.7362],
        [2.4875, 3.4212, 2.1066]])


In [42]:
# create training example..
# preventing weights history by apply grad.zero_()
weights = torch.ones(4, requires_grad = True)
for epoch in range(2):
  model_output = (weights * 3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
