<a href="https://colab.research.google.com/github/Ezzaldin97/pytorch-coding/blob/main/pyTorch_DL_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# everything in pytorch is based on Tensor, considered as main Data Structure
import torch
# torch.empty(size(n_dim))
x = torch.rand(1, 2)
print(x)
x = torch.empty(2, 2, 3)
print(x)
x = torch.ones(2, 3, 4, dtype = torch.int8)
print(x)
print(x.dtype)
# create a tensor from python list..
x = torch.tensor([3.5, 66])
print(x)

tensor([[0.0286, 0.7848]])
tensor([[[6.3632e-35, 0.0000e+00, 3.9236e-44],
         [0.0000e+00,        nan, 0.0000e+00]],

        [[1.3556e-19, 8.6462e+11, 3.2778e+09],
         [1.4988e+10, 3.2522e+03, 1.3023e+01]]])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int8)
torch.int8
tensor([ 3.5000, 66.0000])


In [9]:
# operations..
# addition
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(torch.add(x, y))

tensor([[0.2092, 0.8096],
        [0.4778, 0.9957]])


In [10]:
# do inplace operation: replace elements in y by addition operation results..
# use _
# add_()
y.add_(x)
print(y)

tensor([[0.2092, 0.8096],
        [0.4778, 0.9957]])


In [11]:
# subtraction
print(torch.sub(x, y))

tensor([[-0.1586, -0.0633],
        [-0.2541, -0.2145]])


In [12]:
# multiplication
print(torch.mul(x, y))
# division
print(torch.div(x, y))

tensor([[0.0106, 0.6042],
        [0.1069, 0.7779]])
tensor([[0.2420, 0.9218],
        [0.4681, 0.7846]])


In [14]:
# slicing..
print(x[:, 0])
print(x[1, 0])

tensor([0.0506, 0.2237])
tensor(0.2237)


In [17]:
# reshaping..
z = torch.rand(2, 4)
print(z)
print(z.view(4, 2))
print(z.view(8))

tensor([[0.6162, 0.1507, 0.0953, 0.3140],
        [0.3704, 0.2234, 0.4617, 0.2515]])
tensor([[0.6162, 0.1507],
        [0.0953, 0.3140],
        [0.3704, 0.2234],
        [0.4617, 0.2515]])
tensor([0.6162, 0.1507, 0.0953, 0.3140, 0.3704, 0.2234, 0.4617, 0.2515])


In [19]:
# converting from numpy to Tensor and Vice Versa
a = torch.ones(2, 5)
print(a)
print(type(a.numpy()))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
<class 'numpy.ndarray'>


In [22]:
import numpy as np
a = np.array([2, 5])
print(type(a))
print(type(torch.from_numpy(a)))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [27]:
# check if GPU Exists
# if exists do the operation on GPU..
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(2, 3, device = device)
  y = torch.rand(2, 3)
  y = y.to(device)
  z = torch.add(x, y)
  z = z.to("cpu")
print(z.numpy())

[[0.6162052  0.15072846 0.0953474  0.31401134]
 [0.37043405 0.22341609 0.46170348 0.25153023]]


In [29]:
# require_grad = True: Tells pytorch to calculate gradient later..
x = torch.ones(2, 3, requires_grad = True)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)